### ISSUE TITLE
getting router inside route callbacks?

### ISSUE THREAD

**Issue by AKST** [philopon/purescript-client-routing#1]
Is it possible to get the setRoute function inside the [router callbacks](https://github.com/philopon/purescript-client-routing/blob/master/examples/Main.purs#L40) much like the [notFound route handler](https://github.com/philopon/purescript-client-routing/blob/master/examples/Main.purs#L43)?

**Comment by philopon** [comment]
It's sounds good! so, I implement and release v0.2.0(It contains some breaking API changes, sorry...). Please try it.

Thanks.

**Comment by AKST** [comment]
Oh awesome, it's already released! I'll try it & let you know if I have any
difficulties
