### ISSUE TITLE
Setting route from outside router definition?

### ISSUE THREAD

**Issue by AKST** [philopon/purescript-client-routing#2]
Hey so wondering if there's a suggested approach for setting the route outside the router definition? Judging by the [type of `setRoute`](https://github.com/philopon/purescript-client-routing/blob/7c4a507c8e0b4091b018c91f3b15bd39cd2c8a65/docs/Network/Routing/Client.md#setroute-1), it looks like I need to do that in the route callback.

``` purescript
setRoute :: String -> Callback _ Unit
```

However, I'd like to do that on a user interface event much like you in a MVC framework such as Ember.js ect. Is there a suggested method of achieving this from the Eff monad?

**Edit:** corrected type

**Comment by philopon** [comment]
Well... Sorry if I don't understand you mentioned. but, EffRouting is just synonym of `Eff (routing :: Routing | eff)`

``` .purs
type EffRouting eff = Eff (routing :: Routing | eff)
```

~~I think you can set route outside of callback using `setRoute`.~~

**Comment by AKST** [comment]
Whoops, wrong type. Will update in just a moment

**Comment by AKST** [comment]
Okay updated

**Comment by philopon** [comment]
Oops, I had forgotten my api design, sorry.

``` .purs
runRouter :: forall eff. RoutingM (routing :: Routing | eff) _ -> EffRouting eff (SetRoute eff)
```

return value of `runRouter` is `SetRoute` type, so please use it.

[example](https://github.com/philopon/purescript-client-routing/blob/master/examples/Main.purs) may also help you.

**Comment by AKST** [comment]
Hmm okay, I see that now. Unfortunately I still have a problem where I want to pass it to code not in scope of that `set` function. I'll show my code if it makes my problem a bit clearer.
1. I've defined my router [like so](https://github.com/AKST/wikit/blob/9898a577ff8d02be5948450c4584166adbe6a6f4/client/src/Main.purs#L24)
2. This is [the code that needs to set the route](https://github.com/AKST/wikit/blob/9898a577ff8d02be5948450c4584166adbe6a6f4/client/src/Components/Query.purs#L65)

In part `2`, I cannot pass the `set` function to this section because it's not available when I'm rendering it inside that route. The only way I think I can, is probably by wrapping it in a `var` and set it out side this code and grab it later, which is kind of ugly and I feel like a nicer solution should be available. (An example of what I'm talking about)

``` purescript
-- imports

main = do
  -- not actual var code, as I don't recall it off the top of my head
  var <- someVar
  set <- runRouter do
    route0 empty do
      set <- getSomeVar var
      liftEff (renderView myMagicallyImportedView { setRoute: set })
 setVar var set
```

I also can't call the `setRoute` function from that location in point 2, due to the return type of `setRoute`. I could probably call `setUnsafeRoute`, but I feel like that's called `setUnsafeRoute` for a reason.

My thoughts is you should be able to do something like this.

``` purescript
-- imports

main = do
  runRouter do
    route0 empty do
      set <- routeSetter
      liftEff (renderView myMagicallyImportedView { setRoute: set })
```

I'm still quite new to purescript, so I might be missing something, but I still feel like I should be able to do that thing above.

**Comment by philopon** [comment]
I got you! I added `routeSetter` as `getSetRoute :: forall eff. Callback (routing :: Routing | eff) (SetRoute eff)` in v0.4.0.
Please try it!

**Comment by AKST** [comment]
Sorry still updating, just currently just fighting with bower hahah. Will update once I get it working

**Comment by AKST** [comment]
Okay I've just done some testing and having a little trouble compiling, and I've just noticed that route0 does not take a function that returns the type `Callback _ _` but type `Eff _ _`, which is inconsistent with the type of `route1` or `route2`, `routeN`, ect, which takes a function that returns `Callback`. I'm guessing this may not be by design and merely an oversight?

**Comment by philopon** [comment]
Oops! I had mistaken. It fixed on v0.5.0. thanks!

**Comment by AKST** [comment]
Awesome I'll try to give it a spin soonish, will let you know how it goes

**Comment by AKST** [comment]
Okay it compiles :+1: I think this solves my problem, thanks for the changes!
